export const PATIENT_SIGNUP_REQUEST = "PATIENT_SIGNUP_REQUEST";
export const PATIENT_SIGNUP_SUCCESS = "PATIENT_SIGNUP_SUCCESS";
export const PATIENT_SIGNUP_FAILURE = "PATIENT_SIGNUP_FAILURE";

export const PATIENT_LOGIN_REQUEST = "PATIENT_LOGIN_REQUEST";
export const PATIENT_LOGIN_SUCCESS = "PATIENT_LOGIN_SUCCESS";
export const PATIENT_LOGIN_FAILURE = "PATIENT_LOGIN_FAILURE";
